### ISSUE TITLE
BFSTest is failing the suite.

### ISSUE THREAD

**Issue by ashish-chopra** [ashish-chopra/Structures#13]
TestBFSOperations is failing the test suite. It was expected `true` but receiving `false`.

**Comment by havanagrawal** [comment]
The test itself is wrong. According to the graph described in tinyGraph.txt, 9 is an isolated node that is not connected to any other node in the graph, and hence hasPathTo(9) will always be false.

**Comment by havanagrawal** [comment]
Hi Ashish, I'd like to contribute more to this repo if possible. Please contact me at havanagrawal@gmail.com, and let me know any way I can contribute. 

Thanks :)
