### ISSUE TITLE
Continuous Integration needed

### ISSUE THREAD

**Issue by ashish-chopra** [ashish-chopra/Structures#19]
Since Structures is growing big, i think this is the right time to integrate CI loop.

**Comment by JainTarunJain** [comment]
I have integrated CI loop using Travis CI. I have also added the build status section in Readme file at root directory that show the status of build.

Refer:  Travis CI added in Structures https://github.com/ashish-chopra/Structures/pull/18

**Comment by ashish-chopra** [comment]
Thank you @JainTarunJain  I have accepted the pull request and closing this issue now. Thanks a lot.
