### ISSUE TITLE
removeAt() is hard coded. Again same silly mistake :(

### ISSUE THREAD

**Issue by ashish-chopra** [ashish-chopra/Structures#8]
```removeAt()``` method called in ```execute(M)``` in ```com.applications.Josephus``` is hard-coded with 2 as parameter. While raising the issue i didn't go into depth, but this seems suspicious.

God!! I really need a good code reviewer!!

**Comment by prakhar96** [comment]
I would like to make the required changes. Also, I would like to change the data structure used from Queue to ArrayList.

**Comment by ashish-chopra** [comment]
Hi Prakhar, you are most welcome to solve the issue. Also please be aware that we are avoiding any kind of class from Java's collection. Since the moto of this repo is to build data structures if that too be built on industry standard data structure then, our classes will remain as just wrappers over them. And it also voilate our vision to learn nitty gritty of writing optimized data structures as mentioned in the referred book.

Kindly read the README. Since i cant able to writing a separate contribution guideline due to shortage of time, you may find some contribution convention stuff in README itself. Also do checkout the "Wiki". I have mentioned four strands - "Data Structures", "Alogrithmic Techniques", "Creative Problems", "Infographics" there. You may contribute in anyone.

Cheers
Ashish

**Comment by prakhar96** [comment]
Okay. Sorry for the inconvenience. So I'll just use the existing LinkedList implementation from this repository.

Thank You

**Comment by ashish-chopra** [comment]
But why you want to change the underlying data structure. Queue is a best fit because it represents the problem statement. As in Josephus Game, people are standing in a queue. And The Queue itself is implemented using LinkedList, so your choice of APIs are already available. What you can do if you want to introduce any new functions you can do inside Josephus, of it is too generic that can be written inside a data structure like Queue, then give it a shot there. But i think removeAt() bug can be solved without any new API function in any data structure.

**Comment by prakhar96** [comment]
Actually, I think that Queue won't be best suited for this problem because Queue is simply FIFO and if I'm removing an element from the middle of the Queue then its simply LinkedList. Also, people are not standing in an ordinary Queue. They're standing in a circular manner that is best represented by Circular LinkedList. 

I'm sorry if I'm going out of the way. In my opinion LinkedList will be better suited.

**Comment by ashish-chopra** [comment]
@prakhar96 : Sorry, i came to see your reply very late. But the way the solution is designed for Josephus is intuitive, based on the problem statement. So the problem is directly modeled using Queue. Let it be that way. But your idea of using a circular LinkedList could be a different way of solving the same question. And it is good to see if you introduce a new CircularLinkedList data structure and write one more josephus implementation as a seperate class and do mention what optimization in terms of time/space complexity you acheived when you modeled the same problem mathematically instead of intuitively.

**Comment by ashish-chopra** [comment]
Meanwhile, i am closing this issue. Thanks @JoshVandeWalle for the pull request.
